package org.csviewer.gui.measure;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public class ProtocolImagePanel extends JPanel {
	/**
	 *  ID generated by Eclipse
	 */
	private static final long serialVersionUID = -4008497306741670560L;
	//private ImageIcon image;
	private static String[] categories = {"Sutures", "Joints", "Skull", 
			"UpperLimb", "LowerLimb"};
	JScrollPane display;
	
	public ProtocolImagePanel(ImageIcon image) {
		//this.image= image;
		JLabel protocolContent = new JLabel(image) {
			public void paintComponent(Graphics g) {
				Color temp = g.getColor();
				// set background color to white
				g.setColor(Color.WHITE);
				g.fillRect(0, 0, 800, image.getImage().getHeight(null));
				g.setColor(temp);
				super.paintComponent(g);
			}
		};
		display = new JScrollPane(protocolContent);
		//protocolContent.setBackground(Color.WHITE); // somehow not working
		display.setPreferredSize(new Dimension(800, 500));
		add(display);
	}

	public ProtocolImagePanel(String caption) {
		this(new ImageIcon("images/protocols/" + caption + ".png"));
	}

	public static String[] getKeys() {
		return categories;
	}

}
