package org.csviewer.gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;

import org.csviewer.dao.MatrilTreeInfo;

public class AnimalSummarytPanel extends JPanel {
	/**
	 * D generated by Eclipse
	 */
	private static final long serialVersionUID = -3189538484135138865L;
	
	private String[] dataNames = {"Unicode:", "Sex:","Birthdate:","B-Group:", 
			"Founder:", "Pedigree:", "MomCode:", "SiblingNo:", 
			"DadCode:", "Status:", "DoD(R):","EAAD(R):"};
	private JTextField[] data = new JTextField[12]; 
	private JPanel summaryPanel, introPanel;
	
	//private SubjectRecordMgr srMgr;

	public AnimalSummarytPanel() {
		createSumPanel();
		createIntroPanel();
		
		this.setLayout(new CardLayout());
		add(introPanel, "intro");
		add(summaryPanel, "summary");
		//summaryPanel.setVisible(false);
		//introPanel.setVisible(true);
	}

	private void createIntroPanel() {
		introPanel = new JPanel();
		JLabel introWording = new JLabel("Animal information will be displayed here "
				+ "when a subject is selected in the family tree.");
		TitledBorder blockBorder = 
				BorderFactory.createTitledBorder("Animal Info Summary");
		introPanel.setBorder(blockBorder);
		introPanel.add(introWording);
	}

	private void createSumPanel() {
		summaryPanel = new JPanel(new GridLayout(2,12));
		JLabel dataLabel;
		JTextField aCell;
		int i = 0;
		Font labelFont = new Font(this.getFont().getFontName(), Font.BOLD,
					this.getFont().getSize());
		for (String name : dataNames) {
			dataLabel = new JLabel(name, JLabel.LEFT);
			dataLabel.setFont(labelFont);
			dataLabel.setOpaque(true);
			dataLabel.setForeground(Color.black);
			//dataLabel.setBorder(blackline);
			// add the cell to the JPanel
			summaryPanel.add(dataLabel);
			
			aCell = new JTextField(12); //JLabel();
			aCell.setEditable(false);
			data[i] = aCell;
			aCell.setForeground(Color.GRAY);
			i++;
			summaryPanel.add(aCell);
		}
		
	}
	
	public void editData(String[] newdata) {
		for(int i = 0; i < 12; i++) {
			data[i].setText(newdata[i]);
		}
		
		((CardLayout) this.getLayout()).show(this, "summary");
	}
	
	public void editData(MatrilTreeInfo newdata)
	{
		data[0].setText(newdata.getUnicode());
		data[1].setText(newdata.getSex());
		data[2].setText(newdata.getDoB());
		data[3].setText(newdata.getBirthGroup());
		data[4].setText(newdata.getMatrilCode());
		data[5].setText(newdata.getPedigree()+"");
		data[6].setText(newdata.getMomUnicode());
		data[7].setText(newdata.getSiblingNo()+"");
		data[8].setText(newdata.getDadUnicode());
		data[9].setText(newdata.getStatus());
		data[10].setText(newdata.getDateOfDoR());
		
		double eeadOrRValue = newdata.getAgeAtDoR();
		String eeadOrRText;
		if (eeadOrRValue == -1)
			eeadOrRText = "(alive)";
		else if (eeadOrRValue == -2)
			eeadOrRText = "(missing)";
		else
			eeadOrRText = ""+eeadOrRValue;

		data[11].setText(eeadOrRText);
		
		((CardLayout) this.getLayout()).show(this, "summary");
	}

}
