package org.csviewer.gui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;

import org.csviewer.dao.MatrilTreeInfo;
import org.csviewer.main.CsvV2MainWindow;

public class CSTreePanel extends JPanel {
	/**
	 *  ID generated by Eclipse
	 */
	private static final long serialVersionUID = -8393348966162528443L;

	private AnimalNodeRenderer anRenderrer = new AnimalNodeRenderer(); 
	
    private JTree tree;
    private CsvV2MainWindow window;

	public CSTreePanel(JTree tree, CsvV2MainWindow window) {
		setLayout(new BorderLayout());
		//theTreePane = new JScrollPane(tree);
		//theTreePane.setPreferredSize(new Dimension(200, 200));
		
		this.window = window;

		this.tree = tree;
		tree.getSelectionModel().addTreeSelectionListener(
    		new TreeSelectionListener() {
            @Override
            public void valueChanged(TreeSelectionEvent e) {
                DefaultMutableTreeNode selectedNode = 
                		(DefaultMutableTreeNode) 
                		tree.getLastSelectedPathComponent();
                if (selectedNode.getUserObject() instanceof MatrilTreeInfo) {
                	MatrilTreeInfo an = (MatrilTreeInfo)selectedNode.getUserObject();
 
                	//Update measure table data
                	// comment out for now
                	System.out.println(an.getUnicode());
                	
                 	// Update Measure information
                	//if (hasMeasure(an.getUnicode()))
                	window.updateMeasureData(an.getUnicode()); 
               	
                	//Update general information
                	window.updateSummaryData(an);
                	//System.out.println(an);
                }
                else {
                	String qCode = selectedNode.getUserObject().toString();
                	System.out.println("Selected founder " + qCode); 
                	window.updateSummaryData(qCode);
                	window.updateMeasureData(qCode);
                }
                	
            }

       });
		JScrollPane theTreePane = new JScrollPane(tree);
    	theTreePane.setPreferredSize(new Dimension(200, 200));
        add(theTreePane, BorderLayout.CENTER);
		
        tree.setCellRenderer(this.anRenderrer);
        //tree.setRootVisible(false);
        tree.setShowsRootHandles(true);
        
        System.out.println("In CSTreePanel...");
        
	}

	public void toggleUnicodeOption() {
		anRenderrer = new AnimalNodeRenderer(!anRenderrer.getUnicodeOption());
		tree.setCellRenderer(anRenderrer); 
		tree.revalidate();
		tree.repaint();
	}

  	class AnimalNodeRenderer extends DefaultTreeCellRenderer {
  		private boolean showUnicode = true;
  		
        Icon nodeIcon;
        final public ImageIcon FEMALE_ICON  = new ImageIcon("images/female_icon.png");
        final public ImageIcon MALE_ICON  = new ImageIcon("images/male_icon.png");
        final public ImageIcon UNKNOWN_ICON  = new ImageIcon("images/unknown_icon.png");
        final public ImageIcon FOUNDER_ICON  = new ImageIcon("images/founder_icon.png");

        public AnimalNodeRenderer() {
        	this(true);
        }

        public AnimalNodeRenderer(boolean showUnicode) {
        	this.showUnicode = showUnicode;
        }

        public boolean getUnicodeOption() {
			// TODO Auto-generated method stub
			return this.showUnicode;
		}

		public void toggleUnicodeOption() {
        	showUnicode = !showUnicode;
		}

		public Component getTreeCellRendererComponent(
                            JTree tree,
                            Object value,
                            boolean sel,
                            boolean expanded,
                            boolean leaf,
                            int row,
                            boolean hasFocus) {

            super.getTreeCellRendererComponent(
                            tree, value, sel,
                            expanded, leaf, row,
                            hasFocus);
            String text; 
            DefaultMutableTreeNode node =
                    (DefaultMutableTreeNode)value;
            Object userObject = node.getUserObject();
            if (userObject instanceof MatrilTreeInfo) {
              	
            	MatrilTreeInfo nodeInfo = (MatrilTreeInfo)userObject;
            	  //Unicode is messy now
            	  //text = nodeInfo.getUnicode();
            	  //change after cleaning up
            	  if (showUnicode)
            		  text = nodeInfo.getUnicode();
            	  else
            		  text = nodeInfo.getUnicode();
            	  
            	  /*
            	  String idWithoutQuote = nodeInfo.getAnimalId().substring(1, 
            			  nodeInfo.getAnimalId().length()-1);
	            */
	            if (hasMeasure(nodeInfo.getUnicode())) {
	            	text = text + "^";
	            }
            }
            else {
          	  text = node.getUserObject().toString();
          	if (hasMeasure(text)) {
            	text = text + "^";
            }
        }
            
            nodeIcon = setNodeIcon(value);
            setIcon(nodeIcon);
            setToolTipText(text);
            setText(text);
            //System.out.println((value.getClass()) + "?Text to render..." + text);

            return this;
        }

        private boolean hasMeasure(String unicode) {
			// return false now
			return window.getBoneMeasureDAO().hasMeasureForUnicode(unicode);
        	//return false;
		}
		
		private Icon setNodeIcon(Object value) {
        	Icon retIcon;
        	
            DefaultMutableTreeNode node =
                    (DefaultMutableTreeNode)value;
 
            if (node.getUserObject() instanceof String)
            	retIcon = FOUNDER_ICON; // handles dummy root node
            else {
            	MatrilTreeInfo nodeInfo =
	                    (MatrilTreeInfo)(node.getUserObject());
          	  //System.out.println(nodeInfo.getUnicode()  + "{" + nodeInfo.getGender().charAt(0) + "}");
          	  
	            String sex = nodeInfo.getSex();
	            //if (nodeInfo.getMomId().length() == 0) {
	  	        // gender is "f" or "m"!!!
	            if (sex.equalsIgnoreCase("F")) {
	            	retIcon = FEMALE_ICON;
	            }
	            else if (sex.equalsIgnoreCase("M")) {
	            	retIcon = MALE_ICON;
	            } else {
	            	retIcon = UNKNOWN_ICON;
	            } 
            }

            return retIcon;
		}
  }
}