package org.csviewer.main;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

import org.csviewer.csdb.CsKinshipTreeFrame;
import org.csviewer.csdb.KinshipGraphEditor;
import org.csviewer.dao.BoneMeasureDAO;
import org.csviewer.dao.FamilyInfoDAO;
import org.csviewer.dao.MatrilTreeInfo;
import org.csviewer.dao.PatrilTreeDAO;
import org.csviewer.gui.AnimalSummarytPanel;
import org.csviewer.gui.CSTreePanel;
import org.csviewer.gui.DataTableViewPanel;
import org.csviewer.gui.MeasureTablePanel;
import org.csviewer.gui.help.CsHtmlWithNaviPanel;
import org.csviewer.gui.image.ImageBlockPanel;
import org.csviewer.gui.measure.MeasureSelectionPanel;
import org.csviewer.gui.measure.ProtocolImagePanel;
import org.csviewer.gui.search.AnimalSetSelectionPanel;
import org.csviewer.mgr.BoneMeasureMgr;
import org.csviewer.mgr.ProjectMgr;
import org.csviewer.mgr.SearchMgr;
import org.csviewer.mgr.analytics.AnalyticsMgr;

public class CsvV2MainWindow extends JFrame {
	/**
	 * ID generated by Eclipse
	 */
	private static final long serialVersionUID = -902805105670159122L;

	public static final Image CS_VIEWER_LOGO = 
			new ImageIcon("images/monkeyicon.png").getImage();
	
	private AnimalSummarytPanel bPanel;
	//private JPanel bPanel;
	private JTabbedPane cPanel;
	private JPanel contentPane;
	
	protected ImageBlockPanel imageBlockPanel = new ImageBlockPanel();
	
	private FamilyInfoDAO mTreeDao = new FamilyInfoDAO();
	private PatrilTreeDAO pTreeDao;
	private SearchMgr sMgr = new SearchMgr(mTreeDao);

	private MeasureTablePanel mPanel = new MeasureTablePanel();
	
	private BoneMeasureDAO boneMeasureDAO = new BoneMeasureDAO();
	private BoneMeasureMgr bmMgr = new BoneMeasureMgr(boneMeasureDAO);
	
	private AnalyticsMgr aMgr = new AnalyticsMgr(sMgr, bmMgr);
	//private AnalyticsMgr aMgr = new AnalyticsMgr(sMgr, boneMeasureDAO);
	
	ProjectMgr pMgr;

	private JMenuBar  jmb;

	public CsvV2MainWindow() {
		super("CSViewer for Analysts - V2.0");
		this.setIconImage(CS_VIEWER_LOGO);
		//mTreeDao = new FamilyInfoDAO();
		
		JMenuBar jmb = prepareMenus();
		
		cPanel = new JTabbedPane();
		//cPanel.setPreferredSize(new Dimension(480, 600));
		//contentPane.add(cPanel);
		/*
		JPanel wPanel = new JPanel();
		wPanel.add(new JLabel("Welcome"));
		cPanel.addTab("Welcome", wPanel);
		*/
		initMainPanel();
        addRightColumn();
		bPanel = new AnimalSummarytPanel();
		bPanel.add(new JLabel("Summary panel goes here..."));
		contentPane.add(bPanel, BorderLayout.SOUTH);
		
		//this.add(contentPane);
		contentPane.setPreferredSize(new Dimension(820, 600));
		add(contentPane);   
		this.setJMenuBar(jmb);
		
		this.pack();
		//CsvV2MainWindow test = new CsvV2MainWindow();
		setVisible(true);
		setLocationRelativeTo(null);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		pMgr = new ProjectMgr(this);
	}

	private void addRightColumn() {
		JPanel rightPanel = new JPanel();
		Dimension fixedSize = new Dimension(375, 600);
		rightPanel.setMaximumSize(fixedSize);
		rightPanel.setPreferredSize(fixedSize);
		rightPanel.setLayout(new BoxLayout(rightPanel, BoxLayout.Y_AXIS));
		rightPanel.add(mPanel);
		imageBlockPanel = new ImageBlockPanel();
		rightPanel.add(imageBlockPanel);
		//rightPanel.add(iPanel);
		add(rightPanel, BorderLayout.EAST);
	}

	private JMenuBar prepareMenus() {
		jmb = new JMenuBar();
		
		createFileMenu();
		
		createSearchMenu();
		
		createFamilyMenu(); 

		createMeasureMenu(); 
		 
		createPathologyMenu(); 
		
		createAnalyticsMenu(); 

        // building the Window menu
		createWindowMenu(); 
		
        // building the Help menu
		createHelpMenu(); 
		
		return jmb;
	}

	private void createAnalyticsMenu() {
        JMenu analyticsMenu = new JMenu("Analytics"); 
        JMenuItem jmItem = new JMenuItem("Measure vs. EAAD");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				//JPanel chartPanel = new SkullMeasurePanel().getChartPanel();
				//new MainDriver().testXyPlotTab(tabbedPane);
				// now using live selection
				//new AnalyticsMgr(sMgr, bmMgr)
				aMgr.setXyPlotMode(AnalyticsMgr.EAAD);
				aMgr.buildXyPlotTab(cPanel); //testXyPlotTab(tabbedPane);
				//MainDriver(bmMgr).testXyPlotTab(tabbedPane, 
				//		sMgr.selectAnimals(), bmMgr.selectMeasures());
			}
        	
        });
        analyticsMenu.add(jmItem);
        
		// Analytics with xy-plot with measure1 as X 
		jmItem = new JMenuItem("Measure-1 as X");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				aMgr.setXyPlotMode(AnalyticsMgr.X_IS_1);
				aMgr.buildXyPlotTab(cPanel); //testXyPlotTab(tabbedPane);
			}
        	
        });
        analyticsMenu.add(jmItem);
 		jmb.add(analyticsMenu);
        
		// Analytics with xy-plot for modeling 
		jmItem = new JMenuItem("Line Fitting");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				aMgr.setXyPlotMode(AnalyticsMgr.EAAD);
				aMgr.buildXyPlotWithLineFitting(cPanel); //testXyPlotTab(tabbedPane);
			}
        	
        });
        analyticsMenu.add(jmItem);
        
		// Analytics with column chart for categorical measures 
		jmItem = new JMenuItem("Column Chart");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				aMgr.buildColumnChartTab(cPanel); 
			}
        	
        });
        analyticsMenu.add(jmItem);
 		
 		// add dynamic head count line chart, using the SubjectHeadCounter
		jmItem = new JMenuItem("Headcount Line Chart");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				aMgr.buildHeadcountChartTab(cPanel);
			}
        	
        });
        analyticsMenu.add(jmItem);
 		
 		// add head count trend chart
		jmItem = new JMenuItem("Head Count Trend");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				JPanel chartPanel = new JPanel();
				chartPanel.add(new JLabel(
						new ImageIcon("images/CSHeadCountBreakdown.png")));
		        JScrollPane scrollPane = new JScrollPane(chartPanel);
				cPanel.addTab("CS Head Count By Year", scrollPane);
				cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}
        	
        });
        analyticsMenu.add(jmItem);
	}

	private void createMeasureMenu() {
        JMenu searchMenu = new JMenu("Measure"); 
        JMenuItem jmItem = new JMenuItem("Select Measure");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent evt) {
				cPanel.addTab("Select Measure", 
						new MeasureSelectionPanel(boneMeasureDAO));
				cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}
        	
        });
        searchMenu.add(jmItem);
        //jmItem = new JMenuItem("Measure Keys");
		JMenu keysSubmenu = new JMenu("Measure Keys");
		loadMeasureKeyItems(keysSubmenu);
		searchMenu.add(keysSubmenu);
        searchMenu.add(jmItem);
        
        jmb.add(searchMenu);
	}

    private void loadMeasureKeyItems(JMenu keysSubmenu) {
    	
		String[] keys = ProtocolImagePanel.getKeys();
		String caption;
		JMenuItem jmItem;
		
		
		ActionListener keySelector = new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				ProtocolImagePanel keyPanel = 
						new ProtocolImagePanel(e.getActionCommand());
		        cPanel.addTab(e.getActionCommand(), keyPanel);
		        cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}

			
		};
		
		for (int i=0; i<keys.length; i++) {
			caption = keys[i];
			jmItem = new JMenuItem(caption);
			keysSubmenu.add(jmItem); 
			jmItem.addActionListener(keySelector);
		}

	}
    
    private void createPathologyMenu() {
    	JMenu jmPathology = new JMenu("Pathology");
    	// The pathology menu lets you show a static image (based on behavior from the given v12 
    	//	bundle *NOT* the given source code! they differ. not sure they're supposed to.)
    	JMenuItem pathologyShowPhotos = new JMenuItem("Show Photos");
    	
    	pathologyShowPhotos.addActionListener(new ActionListener() {
    		@Override
    		public void actionPerformed(ActionEvent e) {
    			openPathologyTab();
    		}
    	});
    	// add menu item to pathology menu
    	jmPathology.add(pathologyShowPhotos);
    	// add pathology menu to global menu bar
    	jmb.add(jmPathology);
    }
    
    private void openPathologyTab() {
    	
    	String tabLabel = "Pathology: Bone Defect";
    	// Used to check if the tab is already open. 
    	int idx = cPanel.indexOfTab(tabLabel);
    	
    	// if it is open already (i.e., it exists; does not return -1) then switch to it
    	if (idx != -1) {
    		cPanel.setSelectedIndex(idx);
    		return;
    	}
    	
    	// else, we have to make it. 
    	JPanel imagePanel = new JPanel(new BorderLayout());
    	// this image is pulled from the bundle; it's 3036 x 2388 native resolution so we have to scale it
    	ImageIcon OGIcon = new ImageIcon("images/#1229 Femur.jpg");
    	Image OGImage = OGIcon.getImage();
    	
    	int targetWidth = 900;
    	int targetHeight = 700;
    	
    	Image scaledImage = OGImage.getScaledInstance(targetWidth, targetHeight, Image.SCALE_SMOOTH);
    	JLabel imageLabel = new JLabel(new ImageIcon(scaledImage));
   
    	// center image within label
    	imageLabel.setHorizontalAlignment(JLabel.CENTER);
    	// center label within panel
    	imagePanel.add(imageLabel, BorderLayout.CENTER);
    	
    	JScrollPane scrollPane = new JScrollPane(imagePanel);
    	cPanel.addTab(tabLabel, scrollPane);
    	// switch focus to newly created tab
    	cPanel.setSelectedComponent(scrollPane);
    	
    }

	private void createSearchMenu() {
        JMenu searchMenu = new JMenu("Search"); 
        JMenuItem jmItem = new JMenuItem("Select Animal");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent evt) {
				/*
				* a placeholder
				JPanel p = new JPanel();
				JLabel l = new JLabel(new ImageIcon("images/monkyIcon.png"));
				p.add(l);
				cPanel.addTab("Animal Selection", p);
				*/
				cPanel.addTab("Animal Selection", 
						new AnimalSetSelectionPanel(sMgr));
				cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}
			
		});
        searchMenu.add(jmItem);
        
        // not doing anything yet 
        jmItem = new JMenuItem("Select Catalog");
        searchMenu.add(jmItem);
        
        // test MeasureTablePanel for now Mar-6-24
        jmItem = new JMenuItem("Select Measure");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent evt) {
				mPanel.showTableCard();
			}
			
		});
        searchMenu.add(jmItem);
        jmb.add(searchMenu);
	}

	private void createWindowMenu() {
		JMenu jmWindow = new JMenu("Window");
		
		JMenuItem jmItem = new JMenuItem("Close Current Window");
		jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				int selectedIndex = cPanel.getSelectedIndex();
				if( ! cPanel.getTitleAt(selectedIndex).equals("Welcome") )
					cPanel.removeTabAt(selectedIndex);
				}
			
		});
		jmWindow.add(jmItem);
		
		jmb.add(jmWindow);
	}

	private void createHelpMenu() {
		JMenu jmHelp = new JMenu("Help");
		
		JMenuItem jmItem = new JMenuItem("About CSViewer");
		jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// update version number ==> to v1.1 now!
				JDialog aboutBox = new JDialog(CsvV2MainWindow.this, 
						"About CS Viewer - Version 2.0");
				aboutBox.setIconImage(CS_VIEWER_LOGO);
				
				//arrangeAboutBox(aboutBox);
				arrangeAboutBoxWithImage(aboutBox);
				aboutBox.pack();
				aboutBox.setVisible(true);
				aboutBox.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
			}

			private void arrangeAboutBoxWithImage(JDialog aboutBox) {
				JButton okButton = new JButton("OK");
				JPanel okButtonPanel = new JPanel();
				okButtonPanel.setLayout(new FlowLayout(FlowLayout.TRAILING));				
				okButtonPanel.add(okButton);
				//okButton.setAlignmentX(JPanel.RIGHT_ALIGNMENT);
				okButton.addActionListener(new ActionListener() {

					@Override
					public void actionPerformed(ActionEvent arg0) {
						aboutBox.setVisible(false);
						aboutBox.dispose();
					}
					
				});
				
				aboutBox.setLayout(new BorderLayout());
				//aboutBox.setLayout(new BoxLayout(aboutBox, BoxLayout.X_AXIS));
				ImageIcon flashIcon = new ImageIcon("images/AboutBoxNoVersion.png");
				aboutBox.add(new JLabel(flashIcon), BorderLayout.CENTER);
				aboutBox.add(okButtonPanel, BorderLayout.SOUTH);
			}
        	
        });
		jmHelp.add(jmItem);
		
		// adding acknowledge page
		jmItem = new JMenuItem("Acknowledgements");
		jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// update version number ==> to v1.1 now!
				JDialog ackBox = new JDialog(CsvV2MainWindow.this, 
						"CSViewer - Acknowledgements");
				ackBox.setIconImage(CS_VIEWER_LOGO);
				try {
					ackBox.add(new AcknowledgementPanel());
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				ackBox.pack();
				ackBox.setVisible(true);
				ackBox.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
				ackBox.setLocationRelativeTo(CsvV2MainWindow.this);
			}
        	
        });
		jmHelp.add(jmItem);

		jmb.add(jmHelp);
	}

	private void createFamilyMenu() {
		JMenu jmFamily = new JMenu("Family");
		
		JMenuItem jmItem = new JMenuItem("Matril Tree");
		jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				JTree maTree = new JTree(mTreeDao.getMaTreeRoot());
				CSTreePanel maTreePanel = new CSTreePanel(maTree,
						CsvV2MainWindow.this);
				cPanel.addTab("Matril", maTreePanel);
				cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}
			
		});
		jmFamily.add(jmItem);
		jmItem = new JMenuItem("Patril Tree");
		jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				pTreeDao = new PatrilTreeDAO(mTreeDao);
				JTree paTree = new JTree(pTreeDao.getPaTreeRoot());
				CSTreePanel paTreePanel = new CSTreePanel(paTree, 
						CsvV2MainWindow.this);
				cPanel.addTab("Patril", paTreePanel);
				cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}
			
		});
		jmFamily.add(jmItem);
		jmb.add(jmFamily);
        jmItem = new JMenuItem("Show Path");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				String typeAndNode = JOptionPane.showInputDialog(
						CsvV2MainWindow.this, 
						"mORp:AnimalId", 
						"Select tree type (m/p) and node (AnimalId)", 
						JOptionPane.INFORMATION_MESSAGE);
				JTree tree;
				char treeType = typeAndNode.charAt(0);
				String animalId = typeAndNode.split(":")[1].trim();
				String tabLabel;
				//FamilyTreeMgr mgr = new FamilyTreeMgr();
				if (treeType == 'm' || treeType == 'M') {
					tree = new JTree(
							CsvV2MainWindow.this.mTreeDao.getMaTreeRoot());
					tabLabel = "Matril-" + animalId;
				}
				else {
					tree = new JTree(
							CsvV2MainWindow.this.pTreeDao.getPaTreeRoot());
					tabLabel = "Patril-" + animalId;
				}
				JPanel p = new CSTreePanel(tree, CsvV2MainWindow.this);
				cPanel.addTab(tabLabel, p);
				cPanel.setSelectedIndex(cPanel.getTabCount()-1);
				//addSelectionListener(tree);
				
				synchronized(p.getTreeLock()) {
					p.validate();
				}
				
				tree.setExpandsSelectedPaths(true);
				//DefaultMutableTreeNode node = mgr.getTestNode();
				String id = typeAndNode.split(":")[1].trim();
				//DefaultMutableTreeNode node = mgr.getMatrilTreeNodeById("i69G3");
				DefaultMutableTreeNode node;
				if (treeType == 'm' || treeType == 'M') 
					node = CsvV2MainWindow.this.mTreeDao.getTreeNodeById(id);
				else
					node = CsvV2MainWindow.this.pTreeDao.getTreeNodeById(id);
				DefaultTreeModel model = (DefaultTreeModel) tree.getModel();
				tree.setSelectionPath(new TreePath(model.getPathToRoot(node)));
			}
        	
        });
        jmFamily.add(jmItem);
        
        jmItem = new JMenuItem("Show Kinship Tree");
        jmItem.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				String animalTattoo = JOptionPane.showInputDialog(
						CsvV2MainWindow.this, 
						"Animal tattoo please...", 
						"Show Kinship Tree for Animal", 
						JOptionPane.INFORMATION_MESSAGE);
				if (!animalTattoo.startsWith("\""))
					animalTattoo = "\"" + animalTattoo + "\"";
				
				KinshipGraphEditor kgEd = new KinshipGraphEditor();
				kgEd.buildGraphforAnimalTopDown(animalTattoo, 3, true);
				//kgEd.buildGraphforAnimal(animalTattoo, 3, true);
				
				JFrame frame = new CsKinshipTreeFrame(kgEd.getKinshipGraph());
				// new GraphFrame(kgEd.getKinshipGraph());
				frame.setTitle("CSViewer - Kinship Tree Display");
		    	frame.setVisible(true);
			}
        });
        jmFamily.add(jmItem);
        
        jmItem = new JMenuItem("Family Interactions");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				JPanel chartPanel = new JPanel();
				chartPanel.add(new JLabel(
						new ImageIcon("images/FamilyInteractions.png")));
		        JScrollPane scrollPane = new JScrollPane(chartPanel);
		        cPanel.addTab("Family Interactions", scrollPane);
		        cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}
        	
        });
        jmFamily.add(jmItem);
        
        // add a separate area for the Toggle Code item
        jmFamily.addSeparator();
        jmItem = new JMenuItem("Show Tattoo");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				/*
				JPanel currPanel = (JPanel) cPanel.getSelectedComponent();
				if (currPanel instanceof CSTreePanel) {
					CSTreePanel treePanel = (CSTreePanel)currPanel;
					treePanel.toggleUnicodeOption();
					//treePanel.reValidateAndRepaint();					
				}
				*/
				JOptionPane.showConfirmDialog(CsvV2MainWindow.this, 
						"Please apply for approval from CPRC", 
						"Notice", JOptionPane.INFORMATION_MESSAGE, 
						JOptionPane.OK_OPTION);
			}
        	
        });
        jmFamily.add(jmItem);
  	}

	private void createFileMenu() {
		JMenu jmFile = new JMenu("File");
		JMenuItem jmItem = new JMenuItem("New");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (pMgr == null)
					pMgr = new ProjectMgr(CsvV2MainWindow.this);
				pMgr.createProjectFolder();
			}
        	
        });

		jmFile.add(jmItem);
		jmb.add(jmFile);
        
        // for displaying dataset as selected in TableView panel
        jmItem = new JMenuItem("Preview");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				JPanel p = new DataTableViewPanel(mTreeDao);
				cPanel.addTab("Preview Dataset", p);
				cPanel.setSelectedIndex(cPanel.getTabCount()-1);
			}
        	
        });
        jmFile.add(jmItem);
        
        // for saving a data set file to the project folder
        jmItem = new JMenuItem("Save");
        jmItem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (pMgr == null)
					pMgr = new ProjectMgr(CsvV2MainWindow.this);
				pMgr.saveSelectedDataset();
			}
        	
        });
        jmFile.add(jmItem);
        jmItem = new JMenuItem("Exit");
        jmFile.add(jmItem);
	}

	private void initMainPanel() {
        contentPane = new JPanel(new BorderLayout());
        contentPane.setOpaque(true);
 
        JPanel output = new CsHtmlWithNaviPanel(null, 
				"images/CSIsland.png");
        JScrollPane scrollPane = new JScrollPane(output);
 
        //Add the text area to the content pane.
        cPanel.addTab("Welcome", scrollPane);       
        
        contentPane.add(cPanel);
	}

	public static void main(String[] args) {
		startCSViewer();
	}

	public void updateSummaryData(MatrilTreeInfo an) {
		this.bPanel.editData(an);
	}

	public void updateSummaryData(String qCode) {
		String[] founderInfo = {qCode, "F", "", "", qCode, 
				"", "", "", "", "", "", ""};
		bPanel.editData(founderInfo);
		repaint();	
	}

	public BoneMeasureDAO getBoneMeasureDAO() {
		return boneMeasureDAO;
	}

	public void updateMeasureData(String unicode) {
		mPanel.editTable(this.boneMeasureDAO.
				getMeasureForUnicode(unicode));
		repaint();	
	}

	public static void startCSViewer() {
       //Schedule a job for the event dispatch thread:
       //creating and showing this application's GUI.
       SwingUtilities.invokeLater(new Runnable(){
           public void run(){
               //Turn off metal's use of bold fonts
        	   UIManager.put("swing.boldMetal", Boolean.TRUE);
               new CsvV2MainWindow();
           }
       });
	}

	public SearchMgr getSearchMgr() {
		return sMgr;
	}

}
